
server:
  port: 8066
  servlet:
    context-path: /security

spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    #????
    timeout: 1209600000ms
    lettuce:
      pool:
        #????????8
        max-active: 8
        #?????????????-1
        max-wait: 10000ms
        #?????????8
        max-idle: 200
        #?????????0
        min-idle: 5
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dwh?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    # ?????? DruidDataSource????? HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 5
      max-wait: 30000
      min-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      filters: stat,wall
      use-global-data-source-stat: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 111111
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*, *.js, *.jpeg, *.jpg, *.png, *.gif, *.css
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 3000
          log-slow-sql: true

#mybatis ?????
mybatis:
  table:
    auto: update
    #create	????????????????????model??????????????????????
    #update	??????????????????????????????????????????????????????
    #none 		?????????
    #add		???/????/????/?????????????????? (????1.0.9.RELEASE?????)?
  model:
    pack: com.example.securitydemon.entry #???????????????????,???
  database:
    type: mysql #????? ?????mysql

mybatis-plus:
  #1.???mybatis ???mybatis???????
  #2.????properties????,???mapperLocations
  mapper-locations: classpath*:mapper/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml


logging:
  level:
    web: debug
    sql: debug

jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "Bearer " #token前缀
  secret: "qwertyuiop7418520" #密钥
  expireTime: 10 #token有效时间 (分钟) 建议一小时以上


#
#  #redis
#  jwt:
#    # JWT??????
#    tokenHeader: Authorization
#    # JWT ????????
#    secret: lzdwtl
#    # JWT???????1000*60*60*24*14?14?????
#    expiration: 1209600000
#    # JWT ???????
#    tokenHead: Bearer